-- Tabela: me_cliente
-- Descrição: Cadastro consolidado de clientes com dados fiscais e de contato
-- Data: 2026-02-03

CREATE TABLE IF NOT EXISTS me_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL REFERENCES me_empresa(id),
    
    -- Dados Principais
    nome_cliente TEXT NOT NULL,
    cpf_cnpj TEXT,
    rg_ie TEXT,
    
    -- Contato
    email TEXT,
    telefone TEXT,
    
    -- Endereço (Armazenado como JSONB para flexibilidade)
    -- Ex: { "cep": "...", "logradouro": "...", "numero": "...", "bairro": "...", "cidade": "...", "uf": "..." }
    endereco JSONB DEFAULT '{}'::jsonb,
    
    -- Metadata
    ativo BOOLEAN DEFAULT true,
    origem TEXT, -- Ex: 'Indicação', 'Google', etc.
    observacoes TEXT,
    foto_url TEXT,
    
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index para busca rápida
CREATE INDEX IF NOT EXISTS idx_me_cliente_empresa ON me_cliente(empresa_id);
CREATE INDEX IF NOT EXISTS idx_me_cliente_nome ON me_cliente(nome_cliente);
CREATE INDEX IF NOT EXISTS idx_me_cliente_cpf_cnpj ON me_cliente(cpf_cnpj);

-- RLS Policies
ALTER TABLE me_cliente ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Empresa pode ver seus clientes" 
ON me_cliente FOR SELECT 
USING (auth.uid() IN (
    SELECT id FROM me_usuario WHERE empresa_id = me_cliente.empresa_id AND id = auth.uid()
));

CREATE POLICY "Empresa pode criar clientes" 
ON me_cliente FOR INSERT 
WITH CHECK (auth.uid() IN (
    SELECT id FROM me_usuario WHERE empresa_id = me_cliente.empresa_id AND id = auth.uid()
));

CREATE POLICY "Empresa pode atualizar seus clientes" 
ON me_cliente FOR UPDATE 
USING (auth.uid() IN (
    SELECT id FROM me_usuario WHERE empresa_id = me_cliente.empresa_id AND id = auth.uid()
));

CREATE POLICY "Empresa pode deletar seus clientes" 
ON me_cliente FOR DELETE 
USING (auth.uid() IN (
    SELECT id FROM me_usuario WHERE empresa_id = me_cliente.empresa_id AND id = auth.uid()
));
